# Generated by Django 5.2.8 on 2025-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoyo',
            fields=[
                ('apo_id', models.AutoField(primary_key=True, serialize=False)),
                ('apo_nombre', models.CharField(max_length=50)),
                ('apo_descripcion', models.TextField()),
                ('apo_capacidad', models.IntegerField()),
            ],
            options={
                'db_table': 'apoyo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaApoyo',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(max_length=50)),
                ('cat_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria_apoyo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('doc_id', models.AutoField(db_comment='Id', primary_key=True, serialize=False)),
                ('doc_nombre', models.CharField(db_comment='Nombre', max_length=255)),
                ('doc_descripcion', models.TextField(db_comment='Descripcion')),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('doex_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'documento_expediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('esp_id', models.AutoField(primary_key=True, serialize=False)),
                ('esp_nombre', models.CharField(max_length=50)),
                ('esp_descripcion', models.TextField()),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecialidadEvaluador',
            fields=[
                ('eseva_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'especialidad_evaluador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_clave', models.CharField(max_length=30, unique=True)),
                ('est_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionExpediente',
            fields=[
                ('eva_id', models.AutoField(primary_key=True, serialize=False)),
                ('eva_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('eva_comentarios', models.TextField(blank=True, null=True)),
                ('eva_fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'evaluacion_expediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('val_id', models.AutoField(primary_key=True, serialize=False)),
                ('var_nombre', models.CharField(max_length=50)),
                ('var_paterno', models.CharField(max_length=50)),
                ('var_materno', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'evaluador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('exp_id', models.AutoField(db_comment='Id', primary_key=True, serialize=False)),
                ('exp_folio', models.CharField(max_length=255)),
                ('exp_curp', models.CharField(db_comment='Curp', max_length=18, unique=True)),
                ('exp_nombre', models.CharField(db_comment='Nombre', max_length=50)),
                ('exp_paterno', models.CharField(db_comment='Paterno', max_length=50)),
                ('exp_materno', models.CharField(blank=True, db_comment='Materno', max_length=50, null=True)),
                ('exp_descripcion', models.TextField(blank=True, db_comment='Descripcion', null=True)),
                ('exp_porcentaje', models.DecimalField(blank=True, db_comment='Porcentaje', decimal_places=2, max_digits=3, null=True)),
                ('exp_fecha_creacion', models.DateTimeField(db_comment='Fecha de creacion')),
                ('exp_inr_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('gen_id', models.AutoField(db_comment='Id', primary_key=True, serialize=False)),
                ('gen_nombre', models.CharField(db_comment='Nombre', max_length=25)),
                ('gen_simbolo', models.CharField(db_comment='Simbolo', max_length=1)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoExpediente',
            fields=[
                ('his_id', models.AutoField(primary_key=True, serialize=False)),
                ('his_comentario', models.TextField(blank=True, null=True)),
                ('his_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('his_fecha_cambio', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial_estado_expediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('ins_id', models.AutoField(primary_key=True, serialize=False)),
                ('ins_nombre', models.CharField(max_length=50)),
                ('ins_descripcion', models.TextField()),
                ('ins_siglas', models.CharField(max_length=1)),
                ('ins_correo', models.CharField(max_length=100)),
                ('ins_numero', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('not_canal', models.CharField(max_length=20)),
                ('not_destino', models.TextField()),
                ('not_asunto', models.CharField(blank=True, max_length=50, null=True)),
                ('not_cuerpo', models.TextField()),
                ('not_estado_envio', models.CharField(max_length=20)),
                ('not_fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('not_fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('per_id', models.AutoField(db_comment='Id', primary_key=True, serialize=False)),
                ('per_fecha_incio', models.DateTimeField(db_comment='Fehca inicio')),
                ('pre_fecha_fin', models.DateTimeField(db_comment='fecha fin')),
                ('pre_nombre', models.CharField(db_comment='Nombre', max_length=25)),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prerrequisito',
            fields=[
                ('pre_id', models.AutoField(db_comment='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prerrequisito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tid_id', models.AutoField(primary_key=True, serialize=False)),
                ('tid_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
    ]
